### ISSUE TITLE
##[error]Empty value for parameter 'output.annotations[0].end_line': undefined

### ISSUE THREAD

**Issue by tinovyatkin** [tinovyatkin/action-eslint#11]

**Comment by EduardoCopat** [comment]
I received this error again while I was running:

```
##[error]Empty value for parameter 'output.annotations[0].end_line': undefined
```

**Comment by EduardoCopat** [comment]
Fixed by cherry-picking 07dd0b9 and transpiling typescript :).

**Comment by lakesare** [comment]
@tinovyatkin, I still get this error. If I use the commit hash in my `.github/workflows/lint.yml` - I get `Error: Cannot find module '@actions/core'`.
Could you publish the `v2` please?
